// Curated Canadian funding programs. Top-level government domains only —
// we deliberately avoid deep-linking to pages that move/expire.
// Always tell users to verify on the official site.

export type FundingType = "grant" | "loan" | "tax_credit" | "wage_subsidy" | "equity";
export type ProvinceCode =
  | "AB" | "BC" | "MB" | "NB" | "NL" | "NS" | "NT" | "NU" | "ON" | "PE" | "QC" | "SK" | "YT";
export type Region = ProvinceCode | "federal";

export type Program = {
  id: string;
  name: string;
  level: "federal" | "provincial" | "regional";
  region: Region | Region[];
  type: FundingType[];
  maxAmount?: string;
  industries: string[] | "all";
  fundingFor: string[];
  who: string;
  what: string;
  url: string;
  notes?: string;
};

export const PROGRAMS: Program[] = [
  {
    id: "sred",
    name: "SR&ED Tax Incentive",
    level: "federal",
    region: "federal",
    type: ["tax_credit"],
    maxAmount: "Refundable up to 35% of eligible R&D spend",
    industries: "all",
    fundingFor: ["r&d", "product development", "experimental development"],
    who: "Canadian-controlled private corporations doing experimental development or applied research.",
    what: "Refundable/non-refundable tax credits on eligible R&D salaries, materials, and contractor costs.",
    url: "https://www.canada.ca/en/revenue-agency/services/scientific-research-experimental-development-tax-incentive-program.html",
  },
  {
    id: "irap",
    name: "NRC IRAP (Industrial Research Assistance Program)",
    level: "federal",
    region: "federal",
    type: ["grant"],
    maxAmount: "Up to ~$10M for large projects; most awards $50k–$500k",
    industries: ["tech", "cleantech", "manufacturing", "biotech", "saas"],
    fundingFor: ["r&d", "product development", "commercialization"],
    who: "Canadian SMEs (≤500 employees) building innovative products or services.",
    what: "Cost-shared funding plus an Industrial Technology Advisor who works with you.",
    url: "https://nrc.canada.ca/en/support-technology-innovation",
  },
  {
    id: "canexport-sme",
    name: "CanExport SMEs",
    level: "federal",
    region: "federal",
    type: ["grant"],
    maxAmount: "Up to $50,000 (50% cost share)",
    industries: "all",
    fundingFor: ["exporting", "international expansion", "trade shows", "market research"],
    who: "Canadian SMEs (1–500 employees, $100k–$100M revenue) entering new export markets.",
    what: "Reimburses 50% of approved international market development costs.",
    url: "https://www.tradecommissioner.gc.ca/funding-financement/canexport/sme-pme/index.aspx",
  },
  {
    id: "sif",
    name: "Strategic Innovation Fund",
    level: "federal",
    region: "federal",
    type: ["grant", "loan"],
    maxAmount: "Project cost typically $10M+",
    industries: ["manufacturing", "tech", "cleantech", "biotech", "agritech"],
    fundingFor: ["r&d", "scale-up", "expansion", "ecosystem building"],
    who: "Larger firms or consortia with major innovation, expansion, or attraction projects.",
    what: "Repayable or non-repayable contributions on big strategic projects.",
    url: "https://ised-isde.canada.ca/site/strategic-innovation-fund/en",
    notes: "Best fit for businesses with $10M+ project budgets.",
  },
  {
    id: "csbfp",
    name: "Canada Small Business Financing Program",
    level: "federal",
    region: "federal",
    type: ["loan"],
    maxAmount: "Up to $1.15M (term loan); $150k (line of credit)",
    industries: "all",
    fundingFor: ["equipment", "real estate", "leasehold improvements", "working capital"],
    who: "For-profit small businesses with ≤$10M annual revenue.",
    what: "Government-shared-risk loans through participating banks. Easier approval than bank-alone loans.",
    url: "https://ised-isde.canada.ca/site/canada-small-business-financing-program/en",
  },
  {
    id: "bdc-loans",
    name: "BDC Financing",
    level: "federal",
    region: "federal",
    type: ["loan", "equity"],
    maxAmount: "From $25k to $25M+",
    industries: "all",
    fundingFor: ["working capital", "equipment", "real estate", "growth", "tech adoption"],
    who: "Canadian businesses of all sizes; BDC is Canada's development bank.",
    what: "Term loans, equity, and advisory services — typically more flexible than commercial banks.",
    url: "https://www.bdc.ca/en/financing",
  },
  {
    id: "ajctc",
    name: "Apprenticeship Job Creation Tax Credit",
    level: "federal",
    region: "federal",
    type: ["tax_credit"],
    maxAmount: "Up to $2,000 per eligible apprentice",
    industries: ["trades", "manufacturing", "construction", "automotive"],
    fundingFor: ["hiring apprentices"],
    who: "Employers hiring apprentices in Red Seal trades.",
    what: "10% non-refundable tax credit on wages paid to first/second-year apprentices.",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/sole-proprietorships-partnerships/business-expenses/apprenticeship-job-creation-tax-credit.html",
  },
  {
    id: "wes",
    name: "Women Entrepreneurship Strategy (WES)",
    level: "federal",
    region: "federal",
    type: ["grant", "loan"],
    maxAmount: "Varies by sub-program",
    industries: "all",
    fundingFor: ["startup", "growth", "ecosystem"],
    who: "Women-owned and women-led businesses across Canada.",
    what: "Umbrella program: includes WES Loan Fund, Inclusive Women Venture Capital, and ecosystem grants.",
    url: "https://ised-isde.canada.ca/site/women-entrepreneurship-strategy/en",
  },
  {
    id: "feddev",
    name: "FedDev Ontario",
    level: "regional",
    region: "ON",
    type: ["grant", "loan"],
    industries: "all",
    fundingFor: ["scale-up", "manufacturing", "innovation", "regional growth"],
    who: "Southern Ontario businesses scaling operations or innovating.",
    what: "Federal regional development agency — multiple programs for SMEs and not-for-profits.",
    url: "https://feddev-ontario.canada.ca/en",
  },
  {
    id: "fednor",
    name: "FedNor",
    level: "regional",
    region: "ON",
    type: ["grant", "loan"],
    industries: "all",
    fundingFor: ["regional growth", "indigenous business", "infrastructure", "tourism"],
    who: "Northern Ontario businesses, communities, and not-for-profits.",
    what: "Federal agency supporting Northern Ontario economic development.",
    url: "https://fednor.canada.ca/en",
  },
  {
    id: "pacifican",
    name: "PacifiCan",
    level: "regional",
    region: "BC",
    type: ["grant", "loan"],
    industries: "all",
    fundingFor: ["scale-up", "innovation", "trade", "indigenous business"],
    who: "British Columbia businesses and organizations.",
    what: "Federal regional development agency for BC.",
    url: "https://www.canada.ca/en/pacific-economic-development.html",
  },
  {
    id: "prairiescan",
    name: "PrairiesCan",
    level: "regional",
    region: ["AB", "SK", "MB"],
    type: ["grant", "loan"],
    industries: "all",
    fundingFor: ["scale-up", "innovation", "agritech", "manufacturing"],
    who: "Alberta, Saskatchewan, Manitoba businesses and organizations.",
    what: "Federal regional development agency for the Prairies.",
    url: "https://www.canada.ca/en/prairies-economic-development.html",
  },
  {
    id: "acoa",
    name: "ACOA (Atlantic Canada Opportunities Agency)",
    level: "regional",
    region: ["NB", "NL", "NS", "PE"],
    type: ["grant", "loan"],
    industries: "all",
    fundingFor: ["scale-up", "innovation", "trade", "tourism"],
    who: "Atlantic Canada businesses and organizations.",
    what: "Federal regional development agency for Atlantic provinces.",
    url: "https://www.canada.ca/en/atlantic-canada-opportunities.html",
  },
  {
    id: "cannor",
    name: "CanNor",
    level: "regional",
    region: ["NT", "NU", "YT"],
    type: ["grant", "loan"],
    industries: "all",
    fundingFor: ["regional growth", "indigenous business", "infrastructure"],
    who: "Yukon, NWT, Nunavut businesses and organizations.",
    what: "Federal regional development agency for Northern Canada.",
    url: "https://www.cannor.gc.ca/eng/",
  },
  {
    id: "oci",
    name: "Ontario Centre of Innovation (OCI)",
    level: "provincial",
    region: "ON",
    type: ["grant"],
    industries: ["tech", "cleantech", "advanced manufacturing", "health"],
    fundingFor: ["r&d", "industry-academia partnerships", "commercialization"],
    who: "Ontario tech and innovation companies, often partnering with universities.",
    what: "Programs like VIP, TalentEdge, and AC³ that match industry with research talent.",
    url: "https://www.oc-innovation.ca/",
  },
  {
    id: "nohfc",
    name: "Northern Ontario Heritage Fund (NOHFC)",
    level: "provincial",
    region: "ON",
    type: ["grant", "loan"],
    industries: "all",
    fundingFor: ["hiring", "infrastructure", "innovation", "tourism"],
    who: "Businesses based in Northern Ontario.",
    what: "Province of Ontario fund for Northern Ontario economic development.",
    url: "https://nohfc.ca/",
  },
  {
    id: "iq",
    name: "Investissement Québec",
    level: "provincial",
    region: "QC",
    type: ["loan", "equity", "grant"],
    industries: "all",
    fundingFor: ["growth", "innovation", "manufacturing", "exporting"],
    who: "Québec businesses of all sizes.",
    what: "Québec's economic-development arm — loans, guarantees, equity, tax credit administration.",
    url: "https://www.investquebec.com/quebec/en",
  },
  {
    id: "innovate-bc",
    name: "Innovate BC",
    level: "provincial",
    region: "BC",
    type: ["grant"],
    industries: ["tech", "cleantech", "life sciences", "digital"],
    fundingFor: ["r&d", "talent", "early-stage", "scale-up"],
    who: "BC tech and innovation companies, often early-stage.",
    what: "Programs like Ignite, Integrated Marketplace, and BC Fast Pilot.",
    url: "https://www.innovatebc.ca/",
  },
  {
    id: "ai-alberta",
    name: "Alberta Innovates",
    level: "provincial",
    region: "AB",
    type: ["grant"],
    industries: ["tech", "cleantech", "energy", "agritech", "health"],
    fundingFor: ["r&d", "commercialization", "scale-up"],
    who: "Alberta-based innovation-driven businesses and researchers.",
    what: "Provincial corporation supporting research and tech commercialization.",
    url: "https://albertainnovates.ca/",
  },
  {
    id: "rmb",
    name: "Research Manitoba",
    level: "provincial",
    region: "MB",
    type: ["grant"],
    industries: ["health", "tech", "agriculture", "natural sciences"],
    fundingFor: ["r&d", "talent", "commercialization"],
    who: "Manitoba researchers and research-focused businesses.",
    what: "Manitoba's research funding agency.",
    url: "https://researchmanitoba.ca/",
  },
];
